### ISSUE TITLE
크롤링 h2-console 에 받아오지 못하는 문제 

### ISSUE THREAD

**Issue by wootaehyeon** [Jhwan02/openSW-team4#9]
🥇 **문제 설명** 🥇 

크롤링한 데이터를 H2 데이터베이스에 저장하려고 시도했으나, H2 Console에서 해당 데이터가 조회되지 않는 문제가 발생했습니다.

해결을 위한 시도
robots.txt 확인
초기 크롤링 대상 사이트였던 링커리어에서 크롤링을 막고 있는 것을 확인했습니다.
확인 결과: 해당 사이트의 robots.txt에 의해 크롤링이 제한됨.

1차 해결 -> 크롤링 대상 변경

크롤링 사이트를 contestkorea로 교체하여 새로운 데이터를 수집하려 했습니다.
하지만 여전히 H2 Console에서 데이터를 확인할 수 없습니다.
재현 방법 (Steps to Reproduce)
크롤링 대상 사이트를 설정하여 데이터를 수집.
크롤링한 데이터를 H2 데이터베이스에 저장.
H2 Console(localhost:8080/h2-console)에서 데이터를 조회 시, 테이블이 비어 있음.

가능한 원인
1. 크롤링 실패 : 대상 사이트에서 크롤링 요청을 차단했을 가능성.
크롤링 코드에서 데이터 파싱 또는 저장 과정에서 오류 발생.
2. 데이터베이스 문제 애플리케이션과 H2 Console이 서로 다른 데이터베이스 인스턴스를 참조하고 있을 가능성.
3. 트랜잭션이 제대로 커밋되지 않았을 가능성.
4. 데이터 저장 로직 문제 : 데이터 삽입 로직이 제대로 동작하지 않거나, 크롤링 데이터가 비어 있는 상태로 저장 시도됨.

🥇 확인 및 요청 사항 

- [x] 크롤링 로그 확인 : 크롤링 데이터가 성공적으로 수집되었는지 확인이 필요합니다.

- [x] 크롤링과 관련된 전반적인 코드 확인과 점검

- [x] H2 Console 설정 점검: H2 Console이 애플리케이션과 동일한 데이터베이스를 참조하고 있는지 확인.

![image](https://github.com/user-attachments/assets/5867091a-37cd-42e4-bb39-e0b306bed879)

**Comment by YHFTF** [comment]
@wootaehyeon
해결 commit : #8d007ebf3a215520a7bf89b67476d0375447895b

**Comment by YHFTF** [comment]
이 문제는 전설의 커밋 8d007ebf3a215520a7bf89b67476d0375447895b 에서 완벽하게 해결되었습니다. 🚀✨
이제 더 이상 이슈가 우리를 괴롭히지 못할 것입니다. 😎

자세한 내용은 8d007ebf3a215520a7bf89b67476d0375447895b 를 참고하세요!
